name: build-and-test
on: [push]
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9", "3.10", "3.11"]

    services:
      service-rserve:
        image: ghcr.io/ralhei/r4.2.2-rserve1.8.12:latest
        ports:
          - 6311:6311
        options: --tty

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip' # caching pip dependencies
      - name: Install dependencies
        run: pip install -r requirements.txt -r requirements_dev.txt
      - name: Run pytest
        run: pytest testing
